version: 2.1

executors:
  my-executor:
    working_directory: ~/project
    docker:
      - image: hashicorp/terraform:0.11.14

jobs:
  test:
    executor: my-executor
    steps:
      - checkout
      - run: 
          name: "Setup AWS environment variables"
          command: |
            echo 'export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"' >> $BASH_ENV
            echo 'export TF_VAR_AWS_ACCESS_KEY_ID="$TF_VAR_AWS_ACCESS_KEY_ID"' >> $BASH_ENV
            echo 'export TF_VAR_AWS_SECRET_ACCESS_KEY="$TF_VAR_AWS_SECRET_ACCESS_KEY"' >> $BASH_ENV
      # - run:
      #     name: "Where Region?"
      #     command: echo ${AWS_DEFAULT_REGION}
      - run:
          name: Init terraform 
          command: |
            echo ${AWS_DEFAULT_REGION}
            echo ${AWS_SECRET_ACCESS_KEY}
            terraform init ~/project/ecs-provision-tf
      - run:
          name: Validate terraform 
          command: terraform validate ~/project/ecs-provision-tf
      - run:
          name: Plan terraform
          command: terraform plan ~/project/ecs-provision-tf

  deploy:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Init terraform
          command: terraform init ~/project/ecs-provision-tf
      - run:
          name: Apply terraform
          command: terraform apply -auto-approve ~/project/ecs-provision-tf
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
