version: 2.1

orbs:
  slack: circleci/slack@3.3.0

executors:
  my-executor:
    working_directory: ~/project
    docker:
      - image: hashicorp/terraform:0.11.14

jobs:
  checkout_code:
    executor: my-executor
    steps:
      # - restore_cache:
      #     keys:
      #       - source-v1-{{ .Revision }}
      #       - source-v1-
      - checkout
      # - save_cache:
      #     key: source-v1-{{ .Revision }}
      #     paths:
      #       - .git
      - run:
          name: Init terraform 
          command: terraform init -input=false ~/project/ecs-provision-tf
      - persist_to_workspace:
          root: ~/project
          paths: ecs-provision-tf
      - run:
          name: Validate terraform 
          command: terraform validate ~/project/ecs-provision-tf
  lint:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: terraform fmt
          command: |
            if [ $(terraform fmt | grep -v .terraform | tee fmt_result.txt | wc -l) -gt 0 ]; then
              echo "Format of this terraform files is not appropriate:"
              echo
              cat fmt_result.txt
              echo
              echo "Please run terraform fmt"
              exit 1
            fi
  plan:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run: terraform plan -input=false -out=terraform.plan ~/project/ecs-provision-tf
      - persist_to_workspace:
          root: ~/project
          paths: ecs-provision-tf
  apply:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Init terraform
          command: terraform init ~/project/ecs-provision-tf
      - run:
          name: Apply terraform
          command: terraform apply -auto-approve ~/project/ecs-provision-tf

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - plan:
          requires:
            - lint
      - slack/approval-notification:
          message: TF Apply Pending approval
          color: '#42e2f4'
          mentions: 'UEXB11CMR'
          webhook: '${SLACK_WEBHOOK}'
          requires:
            - plan
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - slack/approval-notification
          filters:
            branches:
              only: master
      - apply:
          requires:
            - hold
          filters:
            branches:
              only: master
